Fix: Hex values can now be prefixed with a '#'
KoalaBotUK/KoalaBot pull request #231
Opened 2021-07-27 11:36 UTC by sudoPom

## Summary

 `close #215 `
## Checklist

- [x] This PR fixes an issue.
- [] This PR adds something new (e.g. new method or parameters).
- [] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [] This PR is **not** a code change (e.g. documentation, README, ...)

<br>

- [x] Have you tested the changes? ([pytest](https://docs.pytest.org/) & [dpytest](https://dpytest.readthedocs.io/))
- [x] Have you followed [PEP-8](https://www.python.org/dev/peps/pep-0008/) for naming and styling?  
- [x] Has your code been properly documented with RestructuredText docstrings?
- [ ] Have you added your changes to `CHANGELOG.md` under the `[Unreleased]` heading?
- [ ] If your code added new bot commands, have you updated `documentation.json`?

<br>

- [x] All of this code is your own, or follows the author repo's licence.

2021-07-27 13:53 UTC, Kaspiaan commented
Please add the new additions to the existing tests, you want to make sure the test code coverage is as high as possible.

2021-07-27 13:58 UTC, JayDwee commented
Also please add all changes including bug fixes to the changelog as mentioned in the checklist

2021-07-28 15:33 UTC, JayDwee commented
Remember, when you think you are done request a review from Kieran, and/or Viraj 
![image](https://user-images.githubusercontent.com/30408869/127351487-fc070e5b-a7c7-47a9-8985-c5ada6ca824f.png)

2021-07-30 13:55 UTC, Kaspiaan commented
Done a review and all looks ok, going to request VIraj also have a look over

2021-07-30 16:16 UTC, Kaspiaan requested changes
Just a tiny change :)

2021-07-30 16:16 UTC, Kaspiaan commented on CHANGELOG.md
> +- Colour strings can now be prefixed with a #
Can you put this under Colour Role please (See previous changelogs)

2021-08-03 11:44 UTC, Kaspiaan approved these changes

2021-08-04 01:34 UTC, merged