Added updated credits list according to contributors list
KoalaBotUK/KoalaBot pull request #272
Opened 2021-10-20 04:13 UTC by Kaspiaan

## Summary
Updates the list of credits in KoalaBot.py, adds Otto to list of senior devs in README.md
close #266

## Checklist

- [x] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [x] This PR is **not** a code change (e.g. documentation, README, ...)

<br>

- [ ] Have you tested the changes? ([pytest](https://docs.pytest.org/) & [dpytest](https://dpytest.readthedocs.io/))
- [ ] Have you followed [PEP-8](https://www.python.org/dev/peps/pep-0008/) for naming and styling?  
- [ ] Has your code been properly documented with RestructuredText docstrings?
- [x] Have you added your changes to `CHANGELOG.md` under the `[Unreleased]` heading?
- [ ] If your code added new bot commands, have you updated `documentation.json`?

<br>

- [x] All of this code is your own, or follows the author repo's licence.

2021-11-01 20:04 UTC, Kaspiaan commented on KoalaBot.py
> +__author__ = "Jack Draper, Kieran Allinson, Viraj Shah, Stefan Cooper, Otto Hooper"
Change to be KoalaBot

2021-11-01 20:18 UTC, JayDwee approved these changes

2021-11-01 20:21 UTC, VottonDev approved these changes
Looks right.

2021-11-01 22:30 UTC, VirajShah18 requested changes

2021-11-01 22:30 UTC, VirajShah18 commented on KoalaBot.py
>  __copyright__ = "Copyright (c) 2020 KoalaBot"
We should also change this line from KoalaBot to KoalaBotUK

2021-11-02 18:24 UTC, VirajShah18 approved these changes

2021-11-02 18:59 UTC, merged