Fix #61
KoalaBotUK/KoalaBot pull request #62
Opened 2020-11-14 18:56 UTC by Unknownlocal

2020-11-14 18:57 UTC, Unknownlocal commented
Fixes #61

2020-11-14 18:58 UTC, JayDwee commented
Pull Master into this branch first

2020-11-14 19:37 UTC, JayDwee requested changes

2020-11-14 19:37 UTC, JayDwee commented on cogs/ReactForRole.py
> +        bot_members = [member for member in guild.members if member.bot and "Koala" in str(member)]
checking for containing Koala isn't the best way and can be exploiited, maybe try something like member.bot and member.id == self.bot.id or something like that

2020-11-14 20:36 UTC, JayDwee requested changes
The bot still doesn't get perms, it just adds itself to the list with no changes to perms

![image](https://user-images.githubusercontent.com/30408869/99156470-edc6d180-26b8-11eb-8665-784ade03da53.png)

2020-11-15 12:32 UTC, JayDwee approved these changes
Looks Good

2020-11-15 12:32 UTC, merged